//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.18 at 03:30:56 PM CEST 
//

package se.vasttrafik.api.departures;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element ref="{}JourneyDetailRef"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{}attlist.Departure"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "",
  propOrder = {
    "journeyDetailRef"
  })
@XmlRootElement(name = "Departure")
public class Departure {

  @XmlElement(name = "JourneyDetailRef")
  protected JourneyDetailRef journeyDetailRef;
  @XmlAttribute(name = "name",
    required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String name;
  @XmlAttribute(name = "sname",
    required = true)
  @XmlSchemaType(name = "anySimpleType")
  protected String sname;
  @XmlAttribute(name = "type",
    required = true)
  protected String type;
  @XmlAttribute(name = "stop",
    required = true)
  protected String stop;
  @XmlAttribute(name = "stopid",
    required = true)
  protected String stopid;
  @XmlAttribute(name = "journeyid",
    required = true)
  protected String journeyid;
  @XmlAttribute(name = "time",
    required = true)
  protected String time;
  @XmlAttribute(name = "date",
    required = true)
  protected String date;
  @XmlAttribute(name = "track")
  protected String track;
  @XmlAttribute(name = "rtTime")
  protected String rtTime;
  @XmlAttribute(name = "rtDate")
  protected String rtDate;
  @XmlAttribute(name = "rtTrack")
  protected String rtTrack;
  @XmlAttribute(name = "direction")
  protected String direction;
  @XmlAttribute(name = "booking")
  protected Boolean booking;
  @XmlAttribute(name = "night")
  protected Boolean night;
  @XmlAttribute(name = "fgColor")
  protected String fgColor;
  @XmlAttribute(name = "bgColor")
  protected String bgColor;
  @XmlAttribute(name = "stroke")
  protected String stroke;
  @XmlAttribute(name = "accessibility")
  protected String accessibility;

  /**
   * Gets the value of the journeyDetailRef property.
   *
   * @return possible object is
   * {@link JourneyDetailRef }
   */
  public JourneyDetailRef getJourneyDetailRef() {
    return journeyDetailRef;
  }

  /**
   * Sets the value of the journeyDetailRef property.
   *
   * @param value allowed object is
   *              {@link JourneyDetailRef }
   */
  public void setJourneyDetailRef(JourneyDetailRef value) {
    this.journeyDetailRef = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the sname property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getSname() {
    return sname;
  }

  /**
   * Sets the value of the sname property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setSname(String value) {
    this.sname = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the stop property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getStop() {
    return stop;
  }

  /**
   * Sets the value of the stop property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setStop(String value) {
    this.stop = value;
  }

  /**
   * Gets the value of the stopid property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getStopid() {
    return stopid;
  }

  /**
   * Sets the value of the stopid property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setStopid(String value) {
    this.stopid = value;
  }

  /**
   * Gets the value of the journeyid property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getJourneyid() {
    return journeyid;
  }

  /**
   * Sets the value of the journeyid property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setJourneyid(String value) {
    this.journeyid = value;
  }

  /**
   * Gets the value of the time property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTime() {
    return time;
  }

  /**
   * Sets the value of the time property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTime(String value) {
    this.time = value;
  }

  /**
   * Gets the value of the date property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getDate() {
    return date;
  }

  /**
   * Sets the value of the date property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setDate(String value) {
    this.date = value;
  }

  /**
   * Gets the value of the track property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTrack() {
    return track;
  }

  /**
   * Sets the value of the track property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTrack(String value) {
    this.track = value;
  }

  /**
   * Gets the value of the rtTime property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getRtTime() {
    return rtTime;
  }

  /**
   * Sets the value of the rtTime property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setRtTime(String value) {
    this.rtTime = value;
  }

  /**
   * Gets the value of the rtDate property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getRtDate() {
    return rtDate;
  }

  /**
   * Sets the value of the rtDate property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setRtDate(String value) {
    this.rtDate = value;
  }

  /**
   * Gets the value of the rtTrack property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getRtTrack() {
    return rtTrack;
  }

  /**
   * Sets the value of the rtTrack property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setRtTrack(String value) {
    this.rtTrack = value;
  }

  /**
   * Gets the value of the direction property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getDirection() {
    return direction;
  }

  /**
   * Sets the value of the direction property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setDirection(String value) {
    this.direction = value;
  }

  /**
   * Gets the value of the booking property.
   *
   * @return possible object is
   * {@link Boolean }
   */
  public boolean isBooking() {
    if (booking == null) {
      return true;
    } else {
      return booking;
    }
  }

  /**
   * Sets the value of the booking property.
   *
   * @param value allowed object is
   *              {@link Boolean }
   */
  public void setBooking(Boolean value) {
    this.booking = value;
  }

  /**
   * Gets the value of the night property.
   *
   * @return possible object is
   * {@link Boolean }
   */
  public boolean isNight() {
    if (night == null) {
      return true;
    } else {
      return night;
    }
  }

  /**
   * Sets the value of the night property.
   *
   * @param value allowed object is
   *              {@link Boolean }
   */
  public void setNight(Boolean value) {
    this.night = value;
  }

  /**
   * Gets the value of the fgColor property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getFgColor() {
    return fgColor;
  }

  /**
   * Sets the value of the fgColor property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setFgColor(String value) {
    this.fgColor = value;
  }

  /**
   * Gets the value of the bgColor property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getBgColor() {
    return bgColor;
  }

  /**
   * Sets the value of the bgColor property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setBgColor(String value) {
    this.bgColor = value;
  }

  /**
   * Gets the value of the stroke property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getStroke() {
    return stroke;
  }

  /**
   * Sets the value of the stroke property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setStroke(String value) {
    this.stroke = value;
  }

  /**
   * Gets the value of the accessibility property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAccessibility() {
    return accessibility;
  }

  /**
   * Sets the value of the accessibility property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAccessibility(String value) {
    this.accessibility = value;
  }

}
